CHANGES, vcspull/__init__.py, vcspull/cli.py, vcspull/testsuite/__init__.py, vcspull/testsuite/helpers.py, vcspull/testsuite/repo_hg.py, vcspull/testsuite/repo_object.py, vcspull/testsuite/repo_svn.py, vcspull/util.py
Move config arguments to -c, add -r / --repomatch, -d / --dirmatch and p...ositional argument namematch, which all accept fnmatch-style args. Add tests to get_repos.
=> Clean and config args to filter through repos

doc/developing.rst
Using pip 8.1.2, test requirements specified using "tests_require"
are not automatically installed.
=> docs/developing: Explicitly install test requirements

tests/test_repo_hg.py
This commit allows contributors interested in
svn and git support to run the test without having to
install mercurial.
=> test_repo_hg: Skip test if hg executable it not installed

vcspull/repo/base.py, vcspull/repo/git.py, vcspull/repo/svn.py
This PR updates vcspull so that it can support:
* git:
* checkout of specific revision or git_tag with exhaustive error checking
* specifying options `git_remote_name` and `tls_verify` as keyword args to `create_repo` 
* svn:
* specifying `svn_username` and `svn_password` as keyword args to `create_repo` (original behavior where username/password are extracted from url is still available)
* checking out a specific svn revision
* specifying  `svn_trust_cert` as keyword args to `create_repo` 
Remaining:
=> Improve svn and git support

CHANGES, poetry.lock, pyproject.toml, requirements/base.txt, tests/conftest.py, tests/test_repo_object.py, vcspull/cli.py
=> Bump libvcs to 0.3.1 - to allow overwriting remote URLs

.github/workflows/tests.yml, CHANGES, README.rst, docs/conf.py, poetry.lock, pyproject.toml, tests/conftest.py, tests/helpers.py, tests/test_cli.py, tests/test_config.py, tests/test_repo_object.py, vcspull/__init__.py, vcspull/cli.py, vcspull/cli_defaultgroup.py, vcspull/config.py, vcspull/exc.py, vcspull/log.py, vcspull/util.py
See also https://github.com/vcs-python/libvcs/pull/271 / libvcs 0.9.0
=> Drop python 2.7

.github/workflows/publish-docs.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, .tool-versions, README.md, poetry.lock, pyproject.toml
- poetry 1.1.7 -> 1.1.12, use new installer
- Drop python 3.6
- Add python 3.10
- CI: test 3.7 and 3.10 (low and high end of supported releases)
- Update myst-parser and sphinx-autodoc-typehints
- Add `.pre-commit-config.yaml`
- black: update 21.9b0 -> 21.12b0
=> CI, package updates, 3.10 support, 3.6 deprecation, add precommit

scripts/generate_gitlab.py
@tony this is the python version of the script we added with #336 for #334 .
It has the same usages as for the bash script, but it also validates that it can write the file and will ask the user if it should overwrite an existing config.
As I said before I'm not a python expert, so if you have any improvement ideas please let me know.
Also I wasn't sure about any style guides this project follows. If you name me the guide I'm happy to format the code accordingly.
Best regards
Segaja
=> add python script to generate config based on gitlab group

CHANGES, tests/conftest.py, tests/test_config_file.py, tests/test_utils.py, vcspull/config.py, vcspull/util.py
- New default config dir is XDG_CONFIG_HOME, Usually ~/.config/vcspull
- Custom config via VCSPULL_CONFIGDIR
- Legacy support until deprecated via LEGACY_CONFIG_DIR (subject to
being removed in future releases)
=> refactor!: Move to `XDG_CONFIG_HOME`

.github/workflows/docs.yml, .github/workflows/tests.yml
See if [recent changes](https://github.com/actions/setup-python/blob/v4/docs/advanced-usage.md#:~:text=Caching%20poetry%20dependencies%3A) / fixes to poetry caching simplify our flow.
This was originally added in https://github.com/vcs-python/libvcs/pull/316 but retracted due to https://github.com/actions/setup-python/issues/374. In recent versions this python version issue has apparently been fixed.
See also: https://github.com/vcs-python/libvcs/pull/394, https://github.com/tmux-python/libtmux/pull/, https://github.com/tmux-python/tmuxp/pull/797
=> ci: Use setup-python v3/4's new caching system

docs/conf.py, poetry.lock, pyproject.toml
- Render changelog in [`linkify_issues`] 
- Fix Table of contents rendering with sphinx autodoc with [`sphinx_toctree_autodoc_fix`]
- Deprecate `sphinx-autoapi`, per above fixing the table of contents issue
This also removes the need to workaround autoapi bugs.
- Test doctests in our docs via [`pytest_doctest_docutils`] (built on [`doctest_docutils`])
[`linkify_issues`]: https://gp-libs.git-pull.com/linkify_issues/
[`sphinx_toctree_autodoc_fix`]: https://gp-libs.git-pull.com/sphinx_toctree_autodoc_fix/
[`pytest_doctest_docutils`]: https://gp-libs.git-pull.com/doctest/pytest.html
[`doctest_docutils`]: https://gp-libs.git-pull.com/doctest
_Fixed via `gp-libs` `v0.0.1a10`_
https://github.com/git-pull/gp-libs/issues/11
=> docs: Move to `gp-libs` (our internal helpers for sphinx)

.github/workflows/tests.yml, CHANGES, Makefile, docs/conf.py, docs/developing.md, poetry.lock, pyproject.toml, scripts/generate_gitlab.py, src/vcspull/cli/sync.py, src/vcspull/config.py, src/vcspull/types.py, tests/conftest.py, tests/fixtures/example.py, tests/test_config.py, tests/test_config_file.py, tests/test_repo.py, tests/test_sync.py
**Requires https://github.com/vcs-python/libvcs/pull/420**
Counterpart to https://github.com/vcs-python/libvcs/issues/362
See also: http://mypy-lang.org/
=> mypy annotations (basic) + libvcs update

CHANGES, docs/cli/sync.md, src/vcspull/cli/__init__.py, src/vcspull/cli/sync.py, src/vcspull/log.py, tests/conftest.py, tests/test_cli.py
Fixes #363, related to #366
CLI sync:
- Fix arguments on sub commands
- Continue to next repo if encountering error when syncing
- New flag: `--exit-on-error` / `-x`
- Also stubs out basic CLI tests
=> Continue on error by default

CHANGES, docs/cli/sync.md, src/vcspull/cli/sync.py, tests/test_cli.py
=> `vcspull sync`: Print msg if repo lookup not in config

CHANGES, docs/cli/sync.md, src/vcspull/cli/sync.py, tests/test_cli.py
=> feat(sync): vcspull sync with no args shows help

CHANGES, docs/conf.py, poetry.lock, pyproject.toml, src/vcspull/_internal/config_reader.py, src/vcspull/config.py, tests/helpers.py, tests/test_config_file.py, tests/test_sync.py
- build(deps): Add types-PyYAML
- Remove kaptan
- Add ConfigReader: 200 lines of code, typed, w/ doctests
=> Move from `kaptan` to `ConfigReader`

CHANGES, MIGRATION, pyproject.toml, src/vcspull/cli/sync.py
- `vcspull sync` file completion support for `-c` and `--config` + <kbd>tab</kbd>
- Backport 1.13.0's notes to migration pages
Similar: https://github.com/tmux-python/tmuxp/pull/834
=> shtab completions (basic), improve migrations docs

CHANGES, src/vcspull/cli/__init__.py, src/vcspull/cli/sync.py, tests/test_cli.py
Purely copy tweaks, except for `sync`, which has a kwarg update.
Since `sync()` has a param change, even though its an internal API, I will bump version for this
=> CLI: Naming cleanup

CHANGES, src/vcspull/cli/__init__.py, src/vcspull/cli/sync.py, tests/test_cli.py
Fix `vcspull sync` behavior when no arguments passed
=> fix(cli[sync]): Fix vcspull sync with no args

CHANGES, poetry.lock, pyproject.toml
To include the massive (internal) refactor from https://github.com/vcs-python/libvcs/pull/430
- build(deps): Bump libvcs 0.18.x -> 0.19.x (sync refactor)
=> libvcs 0.19.0

.tmuxp.yaml, CHANGES, conftest.py, docs/conf.py, pyproject.toml, scripts/generate_gitlab.py, src/vcspull/_internal/config_reader.py, src/vcspull/cli/__init__.py, src/vcspull/cli/sync.py, src/vcspull/config.py, src/vcspull/log.py, src/vcspull/types.py, src/vcspull/util.py, src/vcspull/validator.py, tests/fixtures/_util.py, tests/fixtures/example.py, tests/helpers.py, tests/test_cli.py, tests/test_config.py, tests/test_config_file.py, tests/test_repo.py, tests/test_sync.py, tests/test_utils.py
See also:
- https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-strict
- https://github.com/vcs-python/libvcs/pull/390
- Fixes #385
=> ci(mypy): Turn on `mypy --strict`
